#!/usr/bin/env bash
set -euo pipefail
set -x

# One-time cluster install for the CUDA training stack. Run from the repo root.
# This intentionally lives outside pyproject dependencies because torch/SGLang/
# veRL versions are CUDA- and cluster-specific.

if [[ -f /etc/profile.d/modules.sh ]]; then
  # shellcheck disable=SC1091
  . /etc/profile.d/modules.sh
  module purge
  module load rhel8/default-amp
  module load gcc/11
  module load cuda/12.1
fi

if [[ -f scripts/env.sh ]]; then
  set +x
  # shellcheck disable=SC1091
  source scripts/env.sh
  set -x
fi

export CUDA_HOME="${CUDA_HOME:-/usr/local/software/cuda/12.1}"
export CUDA_PATH="$CUDA_HOME"
export PATH="${LOCAL_BIN_DIR:-$HOME/.local/bin}:$CUDA_HOME/bin:$PATH"
GCC_LIBSTDCPP_DIR="$(dirname "$(g++ -print-file-name=libstdc++.so.6)")"
export LD_LIBRARY_PATH="$GCC_LIBSTDCPP_DIR:$CUDA_HOME/lib64:${LD_LIBRARY_PATH:-}"
unset CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH CUDA_INC_PATH

if ! command -v uv >/dev/null 2>&1; then
  echo "uv is not on PATH. Install uv or add it to PATH before running this script." >&2
  exit 1
fi

retry_cmd() {
  local attempt=1
  local attempts="${UV_INSTALL_RETRIES:-3}"
  local delay_s="${UV_INSTALL_RETRY_DELAY_S:-20}"
  while true; do
    if "$@"; then
      return 0
    fi
    if [[ "$attempt" -ge "$attempts" ]]; then
      return 1
    fi
    echo "Command failed; retrying in $((delay_s * attempt))s ($attempt/$attempts): $*" >&2
    sleep "$((delay_s * attempt))"
    attempt="$((attempt + 1))"
  done
}

write_torch_constraints() {
  TORCH_CONSTRAINTS_FILE="${TORCH_CONSTRAINTS_FILE:-$CACHE_ROOT/constraints/torch-stack.txt}"
  mkdir -p "$(dirname "$TORCH_CONSTRAINTS_FILE")"
  python - "$TORCH_CONSTRAINTS_FILE" <<'PY'
from importlib.metadata import PackageNotFoundError, version
import sys

out_path = sys.argv[1]
names = ["torch", "torchvision", "torchaudio", "triton"]
with open(out_path, "w", encoding="utf-8") as handle:
    handle.write("# Generated by scripts/cluster/install_verl_stack.sh\n")
    for name in names:
        try:
            handle.write(f"{name}=={version(name)}\n")
        except PackageNotFoundError:
            pass
print(f"Wrote Torch stack constraints to {out_path}")
PY
  export TORCH_CONSTRAINTS_FILE
}

uv_pip_install_constrained() {
  retry_cmd uv pip install --constraint "$TORCH_CONSTRAINTS_FILE" --extra-index-url "$PYTORCH_INDEX_URL" "$@"
}

PYTHON_VERSION="${PYTHON_VERSION:-3.11}"
if [[ "${RECREATE_VENV:-0}" == "1" && -d "$VENV_DIR" ]]; then
  rm -rf "$VENV_DIR"
fi

if [[ -x "$VENV_DIR/bin/python" ]]; then
  VENV_PYTHON_VERSION="$("$VENV_DIR/bin/python" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
  if [[ "$VENV_PYTHON_VERSION" != "$PYTHON_VERSION" ]]; then
    echo "Existing venv uses Python $VENV_PYTHON_VERSION, but PYTHON_VERSION=$PYTHON_VERSION." >&2
    echo "Set RECREATE_VENV=1 to rebuild $VENV_DIR, or remove it manually." >&2
    exit 1
  fi
fi

retry_cmd uv sync --python "$PYTHON_VERSION" --extra verl

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

PYTORCH_INDEX_URL="${PYTORCH_INDEX_URL:-https://download.pytorch.org/whl/cu121}"
TORCH_SPEC="${TORCH_SPEC:-torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1}"

if [[ "${INSTALL_TORCH:-1}" == "1" ]]; then
  # shellcheck disable=SC2086
  retry_cmd uv pip install --index-url "$PYTORCH_INDEX_URL" $TORCH_SPEC
fi
write_torch_constraints

uv_pip_install_constrained -U "ray[data,train,tune,serve]"

VERL_SRC="${VERL_SRC:-$CACHE_ROOT/src/verl}"
if [[ ! -d "$VERL_SRC/.git" ]]; then
  mkdir -p "$(dirname "$VERL_SRC")"
  git clone https://github.com/verl-project/verl.git "$VERL_SRC"
else
  git -C "$VERL_SRC" pull --ff-only
fi

uv_pip_install_constrained -e "$VERL_SRC[sglang]"

SGLANG_SPEC="${SGLANG_SPEC:-sglang==0.5.8}"
uv_pip_install_constrained "$SGLANG_SPEC"

FLASH_ATTN_SPEC="${FLASH_ATTN_SPEC:-flash-attn}"
if [[ "${INSTALL_FLASH_ATTN:-0}" == "1" ]]; then
  uv_pip_install_constrained -U packaging psutil ninja
  retry_cmd env MAX_JOBS="${MAX_JOBS:-4}" uv pip install --constraint "$TORCH_CONSTRAINTS_FILE" --extra-index-url "$PYTORCH_INDEX_URL" --no-build-isolation "$FLASH_ATTN_SPEC"
fi

python - <<'PY'
import os
import importlib.util
from pathlib import Path
import torch

for name in ["verl", "ray", "sglang", "torch"]:
    if importlib.util.find_spec(name) is None:
        raise SystemExit(f"missing {name}")
if importlib.util.find_spec("sglang.srt") is None:
    raise SystemExit("missing sglang.srt runtime module")
if os.environ.get("INSTALL_FLASH_ATTN") == "1" and importlib.util.find_spec("flash_attn") is None:
    raise SystemExit("missing flash_attn")

constraints = {}
constraint_path = os.environ.get("TORCH_CONSTRAINTS_FILE")
if constraint_path and Path(constraint_path).exists():
    for line in Path(constraint_path).read_text(encoding="utf-8").splitlines():
        if "==" in line and not line.startswith("#"):
            name, value = line.split("==", 1)
            constraints[name] = value
    expected_torch = constraints.get("torch")
    if expected_torch and torch.__version__ != expected_torch:
        raise SystemExit(f"torch drifted to {torch.__version__}; expected {expected_torch}")

print("torch", torch.__version__)
print("torch cuda available", torch.cuda.is_available())
if torch.cuda.is_available():
    print("cuda device count", torch.cuda.device_count())
    print("cuda device 0", torch.cuda.get_device_name(0))
PY
